### ISSUE TITLE
lib64/limb.so.6 version 'GLIBC_2.23' not found

### ISSUE THREAD

**Issue by ernesto84** [conda/conda-pack#104]
I have packed an environment on a VM with RH 8.1. I am able to activate that environment on a RH 7.7 (Maipo) machine. However, when I launch python and try to import tensorflow, I get the above error. I tried to change LD_LIBRARY_PATH to point to the lib path of the environment, but that didn't work either. The environment still looks for libraries in ~/lib64/. Any advice?

**Comment by mcg1969** [comment]
I would like to suggest this is an issue with tensorflow and not conda-pack. Here's a relevant issue:
https://github.com/tensorflow/tensorflow/issues/28660
