### ISSUE TITLE
Maintenance of this package

### ISSUE THREAD

**Issue by jcrist** [conda/conda-pack#108]
I am no longer employed at Anaconda, and no longer have time to maintain this package. It would be nice if someone at Anaconda (or in the conda community) could take on general maintenance. My personal stance is that conda-pack is feature complete, but may have bugs (particularly on windows, or as conda's format changes over time). I'm happy to provide periodic feedback, but don't really have the time to handle and respond to issues and PRs in a timely manner.

cc @conda/conda-core

**Comment by xhochy** [comment]
Thanks for the information @jcrist. I'm an active user of this and would have a bit of time to take on maintenance just enough to keep this alive.

**Comment by jcrist** [comment]
Thanks @xhochy. I'd be happy to give you commit access to this repo, but I don't have permissions.

To @conda/conda-core - I can vouch that @xhochy is a responsible and careful developer, and would trust him with maintenance of this package.

**Comment by jjhelmus** [comment]
@jcrist I would be happy to help maintain this project and can get all the permissions and bits on the Anaconda side in line.

**Comment by jcrist** [comment]
Hooray! Thanks @jjhelmus & @xhochy for stepping up here.

**Comment by jjhelmus** [comment]
@xhochy You should receive an invite that grants commit access to this repository.

**Comment by xhochy** [comment]
Thanks that worked.

**Comment by mcg1969** [comment]
Yep, we're definitely committed to seeing this package maintained and improved. Of course we're all busy folks but it's proving very useful and we want to see it flourish!

**Comment by mcg1969** [comment]
I'm going to close this now that we're up and running!
