### ISSUE TITLE
SquashFS support

### ISSUE THREAD

**Issue by rafiyr** [conda/conda-pack#110]
Feature request: add output support for using squashfs as the output archive format.

I would like to use some environments without unpacking.  So far it seems to work fine as long as I either squash the environment directly (but it has to be created in the same path that will be used for mounting), or if I pack with a specified destination, but that requires the extra step of untarring just to squash it.

**Comment by mcg1969** [comment]
I would absolutely be open to receiving a PR for this, but under the condition that it not introduce additional mandatory dependencies into the package. It's fine if it relies on _optional_ dependencies (like, say, PySquashfsImage). It really does sound like a compelling idea.
