### ISSUE TITLE
Does conda-pack packs `pkgs` directory?

### ISSUE THREAD

**Issue by prclibo** [conda/conda-pack#112]
Hi,

I use `conda install cudatoolkit-dev -c conda-forge` to maintain CUDA libraries. It will install a full cuda library and header suite in `$CONDA_PREFIX/pkgs`. I found that this folder is not packed running conda-pack. Is there a way to add this folder into the tarball? Tried with `--include` option but seems not work.

**Comment by mcg1969** [comment]
`pkgs` is the package cache. There should be no functional reason for `conda-pack` to include it, because the cuda library and header suite should be installed into the environment where it is being used. Are you trying to access it directly from `pkgs`? That's a no-no :-)

**Comment by prclibo** [comment]
@mcg1969 Thanks for the reply. There are two `pkgs` dir in conda.

1. `~/anaconda3/pkgs` is the package cache you mentioned.
2. `~/anaconda3/envs/<env_name>/pkgs` is the directory where packages like `cudatoolkit-dev` install their additional binaries.

What I mean is the second one.

**Comment by mcg1969** [comment]
Wow, is that so? That's actually quite bad. Because now, if you install that package in the root environment, it clobbers the package cache. And I'm reasonably sure the package building machinery guards against this by forbidding packages from putting files there.

**Comment by prclibo** [comment]
I didn't meet this problem since I seldom install packages in the base env.

The usage of `cudatoolkit-dev` is as https://stackoverflow.com/a/61253367/2943445

The package seems a wrapper of the NVIDIA CUDA install shell script, which might explain how it override the building guards you mentioned.

A copy of my installed env folder:

```
li@li-B450M-DS3H:~/anaconda3/envs$ tree pytorch/pkgs/ -L 2
pytorch/pkgs/
├── cuda-toolkit
│   ├── bin
│   ├── cuBLAS
│   ├── doc
│   ├── extras
│   ├── include
│   ├── lib64
│   ├── libnsight
│   ├── libnvvp
│   ├── nsight-compute-2019.4.0
│   ├── nsight-systems-2019.3.7.5
│   ├── nsightee_plugins
│   ├── nvml
│   ├── nvvm
│   ├── share
│   ├── src
│   ├── tools
│   └── version.txt
└── cudatoolkit-dev

18 directories, 1 file
```

**Comment by mcg1969** [comment]
This is just bad practice. The `pkgs` directory in the root environment is used by conda as its package cache, and that is why conda-pack does not include it in its archives.

Conda environments should not be depending upon this directory's existence for their proper operation. Indeed, it's a good practice to blow away this directory when building Docker images of conda environments to save space.

This package is simply incompatible with conda-pack and will remain so. As a user of the package I would strongly encourage you to press the conda-forge package maintainers to modify their approach, and put its files somewhere else.
