### ISSUE TITLE
Question regarding source and target environments "os type" 

### ISSUE THREAD

**Issue by dutta1kartik3** [conda/conda-pack#115]
Under the Caveats section of the home page (https://conda.github.io/conda-pack/#caveats) it says that "the os type where the environment was built must match the os type of the target". 
Does this mean that a conda environment packed in Ubuntu won't work in Amazon Linux?

I wanted to confirm since (https://www.anaconda.com/blog/moving-conda-environments) seems to suggest so. Thanks!

**Comment by jjhelmus** [comment]
When the documentation mentioned os type the intention is macOS vs Linux vs Windows.  Packs are intended to be compatible between different distributions of Linux.
