### ISSUE TITLE
conda-unpack does not change RPATHs

### ISSUE THREAD

**Issue by e-thereal** [conda/conda-pack#117]
Scope
====

When installing C++ binaries into an existing conda environment on Linux, typically the RPATH of the binaries is set to the conda lib directory so that dependencies are searched for in the conda environment. When packing an environment and installing it on a different machine, the RPATH is not changed by conda-unpack and consequently the default directory for looking for dependencies is still the path that was used to create the environment.

Tested using conda-pack v0.4.0 installed from conda-forge.

Proposed fix
========

Extend conda-unpack to also reset the RPATH of all binaries to the unpacked CONDA_PREFIX in case the RPATH is still set to the old environment path (the environment that was packaged).

**Comment by e-thereal** [comment]
Or to put it differently, will the RPATH substitution work, when all binaries are installed as a conda package and not simply copied into the conda environment using, e.g,  "make install"? When this could be a workaround, although it would be quite handy if conda-pack could still package the environment as is, no matter how the files came about, but I understand that this might be difficult to solve in a general way.

**Comment by nehaljwani** [comment]
When you build/install these binaries, add `$ORIGIN/../lib` to the RPATH, so that you don't require patching them on unpacking.

**Comment by e-thereal** [comment]
Thanks for the quick reply. I'll try that. I also just found out that manually adding my binaries to the conda-unpack script also changes the RPATH, so there are already several possible fixes. I'll try your solution and get back to you as soon as possible.
