### ISSUE TITLE
Multiple damaged tar archives errors, instructions not applicable to Windows users

### ISSUE THREAD

**Issue by brethvoice** [conda/conda-pack#136]
I followed the instructions but they are clearly meant for a UNIX-based operating system.  They fail for Windows; I got dozens of "Damaged tar archive" and "Retrying" messages, and had to make the forward slashes (`/`) back-slashes (`\`) to even get Windows command prompt to look for `.\my_env\bin\Python` which apparently should have been closer to `.\my_env\Library\bin\Python` or similar, but still failed.

I still cannot figure out how to make this work for Windows.  I built the tar.gz file using `conda-pack` installed on a miniconda base environment to save out another conda environment, then transferred to another computer with the same operating system (Windows 10).

**Comment by mcg1969** [comment]
@brethvoice sorry you're having problems. I would definitely recommend the .zip format for Windows, but I also believe the latest tagged builds include fixes for `.tar.gz` support on Windows. It might be worth another shot.

**Comment by mcg1969** [comment]
I'm going to go ahead and close this issue. I do hope the newer versions are helpful for you, but if not, we'll need a very specific reproducible example to help. Ideally, we need clear steps to create an environment that breaks conda-pack in the ways you're observing!

**Comment by mcg1969** [comment]
So in other words, feel free to either open a new issue with this example if you have one!
