### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jcrist** [conda/conda-pack#14]
This currently only supports linux/osx/*nix-likes. Some windows specific behaviors have been added, but the tests currently fail on windows (partly due to `/` vs `\` handling).

**Comment by certik** [comment]
Do you want to use Azure pipelines to test on Win/Mac/Linux at the same place, or do you prefer the combination of Travis for Linux+Mac and Appveyor for Win?

**Comment by jcrist** [comment]
No strong thoughts. I have no experience using azure pipelines, and travis/appveyor have been sufficient so far.

**Comment by jcrist** [comment]
If you're looking at adding windows support, you might want to look at #48 where work is currently ongoing.

**Comment by jcrist** [comment]
Fixed by #48.
