### ISSUE TITLE
Release conda-pack

### ISSUE THREAD

**Issue by johnhany97** [conda/conda-pack#140]
Hello,

Would it be possible to cut a release of conda-pack? I'd like to be able to use conda-pack with this feature https://github.com/conda/conda-pack/pull/109

I see the last release was cut quite a while back, any reason we're blocking on a release?

Thanks for your time

**Comment by delta003** [comment]
@mcg1969 Can you maybe help with this? I saw you recently committed to this repository

**Comment by mcg1969** [comment]
Good point @johnhany97 @delta003 . Let me do a quick review of the newer issues and assuming nothing fatal I'll tag a release.

**Comment by mcg1969** [comment]
I've tagged 0.5.0

**Comment by brianpiper** [comment]
@mcg1969 Sorry to resurrect this, but when will the new release be available on conda or pypi?

**Comment by mcg1969** [comment]
Thanks for the ping, @brianpiper. I'll work on conda-forge. PyPi is going to take me longer.

**Comment by ericdill** [comment]
the conda-forge recipe is currently pulling from pypi so you'll need to rework a bit of the meta.yaml to pull directly from github. Ping me when you get the conda-forge PR in and I can merge it. Make sure to add yourself as a maintainer too

**Comment by mcg1969** [comment]
Thanks @ericdill, I did just that.

**Comment by ericdill** [comment]
conda-forge PR is merged. Package should be available within 30-60 mins based on the update timing of cloudflare
