### ISSUE TITLE
Handling forward slash paths on Windows

### ISSUE THREAD

**Issue by djhoese** [conda/conda-pack#141]
I'm attempting to use conda-pack on an environment that uses conda-forge packages and includes the PyQt5 and Qt packages. As part of these installations (at least from conda-forge) there is a pre-link hook that creates a `<env>/qt.conf` file and a `<env>/Library/bin/qt.conf` file. These are copies of each other.

In this file we have content such as:

```
[Paths] 
Prefix = C:/Users/User/Miniconda3/envs/conda_unpack_test/Library
Binaries = C:/Users/User/Miniconda3/envs/conda_unpack_test/Library/bin
Libraries = C:/Users/User/Miniconda3/envs/conda_unpack_test/Library/lib
Headers = C:/Users/User/Miniconda3/envs/conda_unpack_test/Library/include/qt
TargetSpec = win32-msvc
HostSpec = win32-msvc
```

Conda-unpack (or rather conda-pack) properly finds this file as something that should have its prefixes updated during conda-unpack. However, conda-unpack assumes that the prefixes will use backslashes (`\\`) as the path separator so the find and replace operation never actually replaces the prefix. Is there any semi-easy way to support the handling of this file whether it be a change to the conda-forge/conda Qt package or to conda-pack?

Some workarounds/hacks:

1. Replace the following lines in conda-unpack-script.py:

   ```
   ('qt.conf', 'C:\\Users\\User\\Miniconda3\\envs\\conda_unpack_test', 'text'),
   ('Library\\bin\\qt.conf', 'C:\\Users\\User\\Miniconda3\\envs\\conda_unpack_test', 'text')
   ```

   With:

   ```
   ('qt.conf', 'C:/Users/User/Miniconda3/envs/conda_unpack_test', 'text'),
   ('Library\\bin\\qt.conf', 'C:\\Users\\User\\Miniconda3\\envs\\conda_unpack_test', 'text')
   ```

   This would of course have to be done after you have the zipped/tarred archive generated by conda-pack.

2. Find/replace the `/` with `\` in the two `qt.conf` files just before running conda-pack. As far as I can tell PyQt5 doesn't like backward slashes and fails so this would have to be reverted if the original source environment was going to be reused.

Edit: Using escaped backslashes (`\\`) works with PyQt5 but then I don't think conda-unpack would find/replace that either by default.

Edit Edit: It does work! So I think regardless of if/when this is fixed I will go with workaround 2 and replace the `/` with `\\` in both `qt.conf` files.

**Comment by mcg1969** [comment]
This is mentioned in #154 as well.
