### ISSUE TITLE
The process cannot access the file

### ISSUE THREAD

**Issue by hassannagy** [conda/conda-pack#142]
I'm attempting to pack my env but every time I try i got this error 
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

this is the full message 
` 
Traceback (most recent call last):
  File "c:\users\hassan\anaconda3\envs\computer_vision_py3.6\lib\site-packages\conda_pack\core.py", line 1014, in finish
    fil.write(script)
  File "c:\users\hassan\anaconda3\envs\computer_vision_py3.6\lib\tempfile.py", line 485, in func_wrapper
    return func(*args, **kwargs)
  File "c:\users\hassan\anaconda3\envs\computer_vision_py3.6\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 10652457-10652458: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hassan\anaconda3\envs\computer_vision_py3.6\lib\site-packages\conda_pack\cli.py", line 148, in main
    ignore_editable_packages=args.ignore_editable_packages)
  File "c:\users\hassan\anaconda3\envs\computer_vision_py3.6\lib\site-packages\conda_pack\core.py", line 466, in pack
    zip_symlinks=zip_symlinks, zip_64=zip_64)
  File "c:\users\hassan\anaconda3\envs\computer_vision_py3.6\lib\site-packages\conda_pack\core.py", line 334, in pack
    packer.finish()
  File "c:\users\hassan\anaconda3\envs\computer_vision_py3.6\lib\site-packages\conda_pack\core.py", line 1021, in finish
    os.unlink(fil.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Hassan\\AppData\\Local\\Temp\\tmpmd_f9cqx' 
`

I attempting many solutions like restart the system and I make sure that only the terminal one terminal use the environment 
this issue on windows 10

**Comment by mjcarter95** [comment]
Experiencing the same issue on Windows 10.

For me, the issue arises after attempting to build a Python package (PyStan) from source (and not via pip/conda install).

**Comment by hassannagy** [comment]
> Experiencing the same issue on Windows 10.
> 
> For me, the issue arises after attempting to build a Python package (PyStan) from source (and not via pip/conda install).

can you solve the problem ?

**Comment by mjcarter95** [comment]
> > Experiencing the same issue on Windows 10.
> > For me, the issue arises after attempting to build a Python package (PyStan) from source (and not via pip/conda install).
> 
> can you solve the problem ?

No, unable to get around it.

**Comment by mcg1969** [comment]
I'm afraid we don't have enough information to go on here. For instance, @hassannagy, a full list of the exact packages in the environment would be helpful.

@mjcarter95, if you're trying to pack and environment that includes packages built from source, I'm not sure we can support that. conda-pack is really only intended to support conda  packages, and pip packages on a best-effort basis.

**Comment by hassannagy** [comment]
> I'm afraid we don't have enough information to go on here. For instance, @hassannagy, a full list of the exact packages in the environment would be helpful.
> 
> @mjcarter95, if you're trying to pack and environment that includes packages built from source, I'm not sure we can support that. conda-pack is really only intended to support conda packages, and pip packages on a best-effort basis.

thanks @mcg1969 I have  `packages built from source` so your comment give me the reason why conda-pack didn't work with me
