### ISSUE TITLE
Resurrect pypi builds

### ISSUE THREAD

**Issue by mcg1969** [conda/conda-pack#143]
@jcrist would you be willing to add me (`mcg1969`) to the PyPi ownership list of conda-pack, so that we can begin pushing new builds there again? Of course, once you've done so we have a little more CI work to do. Thanks!

**Comment by johnhany97** [comment]
@mcg1969 any other thoughts on how we could get release 0.5.0 onto PyPi?

**Comment by jcrist** [comment]
Apologies for the delayed response here, this slipped through the cracks. I've added Michael as an owner on pypi. Let me know if there's anything else needed here.

**Comment by mcg1969** [comment]
https://pypi.org/project/conda-pack/0.5.0/
