### ISSUE TITLE
Add parcel support

### ISSUE THREAD

**Issue by mcg1969** [conda/conda-pack#144]
I was investigating the parcel format and some of Anaconda's own code for creating them, and I realized that there is a tremendous amount of overlap between parcels and conda-packs—enough that it would require only a small modification to this code base to provide that support. In effect, a parcel is just a `.tar.bz2` format with an additional directory with a small amount of parcel-specific data (a manifest and activation script).

Our own code for parcel building employs some of the very pre-emptive relocatability logic that conda-pack users (shebang rewriting).

For this reason I think we should formally add parcel support.

**Comment by mcg1969** [comment]
Working on this here: #146

**Comment by jcrist** [comment]
Is there a reason to port over parcel creation to conda-pack? Are there external users that have asked for this functionality? Parcels are sufficiently different from other formats (extra metadata file needed, no `conda-unpack` script can be run (afaik), etc...), I'm not convinced that parcels make sense to including in `conda-pack`, even if there is some overlap in code. Up to you though, I admit I'm not the one doing the work here :).

**Comment by mcg1969** [comment]
We see a significant amount of demand for parcel creation. And while they are not specifically asking that conda-pack be enhanced with that support that doesn't seem like a necessary criterion, particularly when the level of code overlap is so significant. The file format differences are quite small: the inclusion of two additional files into the archive—only one of them dynamically generated, and particular values of `arcroot` and `dest-prefix` basically take care of the rest.

**Comment by mcg1969** [comment]
Provided in the current dev builds by #146. Now that we're posting intermediate builds to the `ctools` channel I am not in a huge hurry to see this in a tagged release. So we can exercise it a bit.
