### ISSUE TITLE
continue to ignore `info` in `load_files()` or just use `--ignore-missing-files`?

### ISSUE THREAD

**Issue by pymonger** [conda/conda-pack#145]
The following error broke our nightlies a few nights ago:

```
$ conda pack --format tar.gz -j -1
Collecting packages...
CondaPackError:
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- python='3.8.5'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).
```

Debugging `core.py`, I found this following entry in `paths.json` is the root cause:

```
$ pwd
/export/home/ops/conda/pkgs/python-3.8.5-h7579374_1/info
$ diff paths.json.orig paths.json
900,905d899
<       "_path": "info/info_json.d/security.json",
<       "path_type": "hardlink",
<       "sha256": "1eba042cbb28d2403ca77fbdd8fb7ca518d65b0522a13730255ffdef694a826a",
<       "size_in_bytes": 1773
<     },
<     {
```

2 ways to solve the error:
1. Use `--ignore-missing-files`
1. Remove `info` from `load_files`: https://github.com/conda/conda-pack/blob/master/conda_pack/core.py#L585

What do you all recommend?

**Comment by mcg1969** [comment]
I prefer #1. However, I just now encountered some clobber issues myself and I feel like `conda-pack` could use much better messaging around this:

1. If there are a small number of these files, it should print the paths to each file being clobbered in the error message.
2. It should recommend these use of `--ignore-missing-files` if the user considers the clobbers to be benign.

**Comment by mcg1969** [comment]
OK, I might be leaning towards #2 now that I've had to wrestle with this in tests :-)

**Comment by mcg1969** [comment]
I think the problem is actually specific to that particular Python 3.8.5 package. I'm talking to the Anaconda Distribution team about it.

**Comment by mcg1969** [comment]
I've decided your idea #2 is the right one. Conda environments composed entirely of well-formed conda packages should have no content in the `info/` directory. Hence ignoring `info` as the current version of conda-pack does is a no-op. But this cuts both ways: ignoring `info/` does nothing, and _not_ ignoring `info/` does nothing, either.

However, a small number of malformed conda packages have cropped up that do install a file in this subdirectory, leading to this missing files exception. So now ignoring the `info/` directory is actually causing problems.

Looking at the commit history, it looks like `info` has been included in the ignore list for at least 3 years, and I don't see a compelling reason to ignore it. That said, I'm still looking. If I find a good reason, I'll revert this change in favor of another approach I'm considering: specifically ignoring `info/` files found in the `paths.json` manifest of conda packages.
