### ISSUE TITLE
Windows: conda-pack prefix replacement inconsistent with conda created envs

### ISSUE THREAD

**Issue by benpapworth** [conda/conda-pack#154]
Simple test:
```
> conda create -n g:\envs\test python qt conda scipy
> conda activate g:\envs\test
> conda pack --dest-prefix g:\envs\foo

> conda create -n g:\envs\foo python qt conda scipy
```

Using diff tool, such as BeyondCompare, to compare g:\envs\foo with test.tar.gz shows these inconsistencies:
* scripts file types (pl, sh, prl, etc.), replacement in scripts is different: conda keeps forward slashes, conda-pack uses back slashes.
* some text files are not updated at all (qt.conf, Library\bin\qt.conf)
* python files contain strings with backslashes which are not escaped (Lib\site-packages\scipy\\_\_config\_\_.py)

While some of the conda prefixes may not be perfect, at least they are tested and known to work. The differences introduced by pack are troubling, especially the python string replacements, as this is frequently seen in 'appdir.py' files.

It would be very helpful if pack used exactly the same code for replacing prefixes as was implemented by conda itself, so this inconsistency couldn't happen.

The same exercise done on Linux doesn't show any difference between the environments.

**Comment by mcg1969** [comment]
The feedback and careful analysis is appreciated! At least some of these observations have been offered previously (e.g., qt.conf) but having them collected here in once place is helpful.

**Comment by benpapworth** [comment]
Many thanks, Michael!

I am hoping to continue giving some helpful feedback; we are avid conda users here, and I personally think that conda is the best way forward for Python package management.

All the best,
Ben
