### ISSUE TITLE
How much can I rely of conda-pack as cross platform

### ISSUE THREAD

**Issue by thebeancounter** [conda/conda-pack#160]
I am using conda-pack to package entire conda env and be able to bundle it with a script.

To what level of cross-platform can I except? Any OS? If built on Linux will any Linux work? If built on Ubuntu will any Debian based work? Same kernel version is needed?

What are the minimal requirements for two OS's to be compatible in that sense and can it be gauranteed?

**Comment by xhochy** [comment]
This is down to the cross-platform compatibility of conda environments. The following things are the constrains you will need to have in mind which conda takes into account when solving the environment on the source system:

- The (g)libc version 
- The cuda version
- The `archspec`, i.e. the instruction sets that the CPU supports.
- The macOS version

Most of the packages have a constraint on neither of the last three ones and can run with a very old (CentOS 6) glibc version. Thus environments with only these packages can be moved around freely on the same operating system (OS in the sense of Win/macOS/Linux) and the same CPU architecture. If one of your packages has a constraint on one of the above points, you can only move the packaged environments to systems that also satisfy these constraints.

Thus if you want to be 100% sure (in 95% of the cases you don't need to be so sure):

* If cuda is used, the cuda version is at least as new as on the source system.
* If on Linux, the glibc version is at least as new as on the source system.
* If on macOS, the macOS version is at least as new as on the source system.
* Our target system should support the same instructions sets your source system has.

All the above constrains are handled through virtual conda packages. You can also enforce support for older versions by manually forcing these virtual packages to different version. This will then increase portability of these environments. But as already said, in most cases, this won't make a difference. Still, you can use a tool like `conda-tree` to see whether any of your packages has a constraint on one of the virtual packages.
