### ISSUE TITLE
Option to export cleanup to minimized environment.

### ISSUE THREAD

**Issue by peterroelants** [conda/conda-pack#163]
Hi conda-pack, first of all: love the tool. I've been using it in my work to create Dockerized environments of conda environments. Using multi-stage Docker builds it allows me to package up the environment without any dependencies on conda and move it to a new clean container. These images are then typically download via various services over a network, so it is important to us to reduce the size of the image.

Having an option in `conda pack` to remove all unnecessary files from the environment would help us minimizing our conda environments (and containers). This option could for example look like `conda pack --clean`, `conda pack --minimize` or `conda pack --essential`.

Some things that I think could be removed are:
- pycache and pyc files
- conda metadata
- man pages
- documentation
And there might be other non-essential files.

Would this feature be aligned with the goals of conda-pack?

**Comment by mcg1969** [comment]
I think this feature would be well aligned with the goals of this tool, yes. In fact, the original developer of `conda-pack` wrote this blog post that captures much of this:

https://jcristharif.com/conda-docker-tips.html

So encapsulating some of this makes sense in conda-pack.

One particular exception is conda metadata. I do not recommend deleting that. I don't think you're going to save that much space, really. And in fact, the unpacking / relocation operation might rely on access to this data.

**Comment by MarioGarbelli** [comment]
Shrink a conda virtual environment could be a very appreciate feature. 
I have a stand alone ~1.3Gb environment in which more then 80% of packages aren't really needed.  
For example, a "static" environment doesn't really need to update / install new packages (package managers should be removed with no impact). Conda toolchain isn't needed too.
