### ISSUE TITLE
Release v0.6.0 on PyPI

### ISSUE THREAD

**Issue by mrakitin** [conda/conda-pack#167]
Hello, do you mind releasing v0.6.0 on PyPI? The latest version there is [0.5.0](https://pypi.org/project/conda-pack/0.5.0/). Thanks!

**Comment by mrakitin** [comment]
Dear maintainers, is there any decision/progress on this request? Thanks!

**Comment by xhochy** [comment]
@mcg1969 @jcrist Can you give me PyPI access, too? Then I would take care of this and also add this as an automated step in the GHA workflow.

**Comment by mrakitin** [comment]
Thank you!

**Comment by mcg1969** [comment]
Happy to do this.

**Comment by xhochy** [comment]
Done: https://pypi.org/project/conda-pack/0.6.0/

Also made a follow-up PR so that the description is rendered correctly on the next release: https://github.com/conda/conda-pack/pull/171

**Comment by mrakitin** [comment]
Thank you, @xhochy!
