### ISSUE TITLE
Conda-pack compatibility with different python versions

### ISSUE THREAD

**Issue by hprovenza** [conda/conda-pack#168]
HI there, I'm considering a use case for conda-pack to deliver an environment to an airgapped computer.   I know that I need to pack the environment on the same kind of OS, and that the destination also needs a conda installation, but I was wondering if the destination's conda also needs the same python version already included, or if the packed env would include that?

What I mean to say is for example:  my source environment is on linux and uses conda with python 3.7.  I pack my env and deliver it to the destination, which has conda with python 3.5.

I imagine two likely outcomes.  1) the compressed env includes python 3.7 and everything will work out of the gate (though the file might be large or 2) the compressed env does not include python and will work on the 3.5 base *if* all the packages in the env are also compatible with 3.5.

Which will it be?  Thanks in advance!

**Comment by mrakitin** [comment]
Hello @hprovenza! I am not a maintainer of the `conda-pack` project but have used it for a while for [NSLS-II deployments](https://gist.github.com/mrakitin/9edd333601b0985b85d66e4009fcc8cf). `conda-pack` packages the environment with the version of Python that is installed into that environment, so you should expect the first outcome. You can experiment with various scenarios using Docker as a build/target platform for testing - you can install a base conda with Python 3.5 there (I believe it's a quite old miniconda prior to v4.4), and then install your packed environment there.

**Comment by xhochy** [comment]
The packed environment should be runnable on a machine without `conda`. Thus the Python versions of your conda installation on the target machine is fully independent of anything in the environment.

**Comment by xhochy** [comment]
Closing this as solved, if there are any issues in the final usage, feel free to open a new issue.

**Comment by mrakitin** [comment]
> The packed environment should be runnable on a machine without `conda`. Thus the Python versions of your conda installation on the target machine is fully independent of anything in the environment.

Hi @xhochy, that is actually great news! Thanks for pointing it out - I re-checked the docs in https://conda.github.io/conda-pack/#commandline-usage, and tried the commands (in particular, `source my_env/bin/activate`) to activate, and then unpack a test env, and it worked well. The habit of using `conda activate ...` caused me to forget about the `source ...` would work. The only inconvenience would be that `conda env list` would not work without activation, but that's not a big deal.
