### ISSUE TITLE
conda-pack problem

### ISSUE THREAD

**Issue by SylvainArd** [conda/conda-pack#169]
Hello,
I have this bug with conda-pack how to fix it please ?
(sylvain) C:\WINDOWS\System32>conda pack -n sylvain -o "C:\Users\Sylvain ARD\Dropbox\Documents Sylvain\autoentrepreneur\Contrats\spores2021\installateur\sylvain.tar.gz"
Collecting packages...
CondaPackError:
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- olefile 0.46:
    lib\site-packages\olefile-0.46.dist-info\installer
    lib\site-packages\olefile-0.46.dist-info\license.txt
    lib\site-packages\olefile-0.46.dist-info\metadata
    + 3 others

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).
Thank you
Best regards

**Comment by xhochy** [comment]
Please post your `conda list` output.

**Comment by SylvainArd** [comment]
(sylvain) C:\Windows\System32>conda list
# packages in environment at C:\Users\Sylvain ARD\.conda\envs\sylvain:
#
# Name                    Version                   Build  Channel
absl-py                   0.5.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astroid                   1.6.5                    py35_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
chardet                   3.0.4                    py35_3    conda-forge
cloudpickle               1.5.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
conda-pack                0.6.0              pyhd3deb0d_0    conda-forge
configparser              4.0.2                    pypi_0    pypi
cycler                    0.10.0                     py_2    conda-forge
cython                    0.28.5           py35h6538335_0    conda-forge
dask-core                 2.6.0                      py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
docutils                  0.14                     py35_1    conda-forge
entrypoints               0.2.3                    py35_2    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
git                       2.30.2               h57928b3_1    conda-forge
grpcio                    1.12.1           py35h1a1b453_0
h5py                      2.8.0            py35hf7173ca_2
hdf5                      1.8.20               hac2f561_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
intel-openmp              2019.4                      245
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.0.1            py35h39e3cac_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.4                    py35_0    conda-forge
jedi                      0.12.1                   py35_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
json5                     0.9.4              pyh9f0ad1d_0    conda-forge
jsonschema                2.6.0                    py35_2    conda-forge
jupyter_client            5.3.3                      py_0    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
jupyterlab                2.1.0                      py_0    conda-forge
jupyterlab_server         1.0.0                      py_0
keras                     2.2.3                    py35_0    conda-forge
keras-applications        1.0.4                      py_1    conda-forge
keras-preprocessing       1.0.2                      py_1    conda-forge
keyring                   13.2.1                   py35_0    conda-forge
kiwisolver                1.0.1            py35he980bc4_2    conda-forge
lazy-object-proxy         1.3.1            py35hfa6e2cd_0    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libgpuarray               0.7.6             hfa6e2cd_1003    conda-forge
libopencv                 3.4.2                h20b85fd_0
libpng                    1.6.37               hfe6a214_1    conda-forge
libprotobuf               3.6.0             h1a1b453_1000    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
lz4-c                     1.9.2                h62dcd97_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.1.3              pyh9f0ad1d_0    conda-forge
markdown                  3.2.1                      py_0    conda-forge
markupsafe                1.0              py35hfa6e2cd_1    conda-forge
matplotlib                2.2.2            py35had4c4a9_2
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.3            py35hfa6e2cd_2    conda-forge
mkl                       2018.0.3                      1
mkl_fft                   1.0.9                    py35_0    conda-forge
mkl_random                1.0.1                    py35_0    conda-forge
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.0                      py_0    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
networkx                  2.4                        py_1    conda-forge
notebook                  5.6.0                    py35_1    conda-forge
numpy                     1.13.3           py35h5c71026_4
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    3.4.2            py35h40b0b35_0
openssl                   1.0.2u               hfa6e2cd_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    0.22.0                   py35_1    conda-forge
pandoc                    2.10.1               he774522_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pickleshare               0.7.5                    py35_0    conda-forge
pillow                    5.3.0            py35h9a613e6_0    conda-forge
pip                       20.2.2                     py_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
protobuf                  3.6.0            py35he025d50_0    conda-forge
psutil                    5.4.7           py35hfa6e2cd_1001    conda-forge
py-opencv                 3.4.2            py35hc319ecb_0
pycocotools               2.0                      pypi_0    pypi
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pygpu                     0.7.6                    py35_0    conda-forge
pylint                    1.9.2                    py35_0    conda-forge
pymysql                   0.10.1                   pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypiwin32                 223                      pypi_0    pypi
pyqt                      5.6.0            py35h764d66f_7    conda-forge
python                    3.5.5                he025d50_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywavelets                1.0.1            py35h452e1ab_0    conda-forge
pywin32                   228                      pypi_0    pypi
pywin32-ctypes            0.2.0                    py35_0    conda-forge
pywinpty                  0.5.4                    py35_2    conda-forge
pyyaml                    3.13             py35hfa6e2cd_1    conda-forge
pyzmq                     17.0.0                   py35_3    conda-forge
qt                        5.6.2           vc14h6f8c307_12
qtawesome                 1.0.1              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.13.0                   py35_0    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
scikit-image              0.14.0           py35h6538335_1    conda-forge
scipy                     1.1.0            py35hc28095f_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.4.3                   py35_0    conda-forge
shutils                   0.1.0                    pypi_0    pypi
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1           py35h6538335_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    3.2.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    3.3.1                    py35_2    conda-forge
spyder-kernels            0.2.6                      py_1    conda-forge
sqlite                    3.32.3               he774522_1    conda-forge
tensorboard               1.10.0                   py35_0    conda-forge
tensorflow                1.10.0                   py35_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.1                    py35_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
theano                    1.0.3                    py35_0    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   5.1.1            py35hfa6e2cd_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_unicode_console       0.5                      py35_0    conda-forge
wincertstore              0.2                   py35_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.10.11          py35hfa6e2cd_1    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11            h62dcd97_1007    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge

(sylvain) C:\Windows\System32>
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le sam. 17 avr. 2021 à 14:10, Uwe L. Korn ***@***.***> a
écrit :

**Comment by xhochy** [comment]
I would guess this comes from another package also installing `olefile`. Sadly you are still using Python 3.5 and for these packages we don't have yet the necessary metadata collected.

@SylvainArd We can help you here but only if you could also post the commands to recreate the environment and also switch to Python >=3.6.

**Comment by jaimergp** [comment]
I am seeing something similar with `ncurses` on a case-insensitive MacOS, so maybe this is due to case-sensitivity issues as well?

**Comment by xhochy** [comment]
@jaimergp Oh! Do you have a reproducer for this? I'm also on a case-insensitive MacOS, so that would be the perfect example for me to dig into this.

**Comment by jaimergp** [comment]
I do, but it is tricky to set up 😬  I am seeing it with `conda-store` setup, which uses Docker Compose. Mounting the volumes on the service brings this up. See here https://github.com/Quansight/conda-store/issues/73

I think I have a workaround, too. I am working on a PR that will compare the `missing_files` sets with the `all_files` set, but all in lowercase. If there's no difference, then it's _probably_ a case-sensitivity issue. I'll send a PR once it is working for me!

**Comment by jaimergp** [comment]
Basically this block: https://github.com/conda/conda-pack/blob/master/conda_pack/core.py#L855-L864

**Comment by jaimergp** [comment]
The main issue is that `os.path.normpath` does not do much on MacOS, compared to Windows.
