### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by xhochy** [conda/conda-pack#173]
We currently build and test for Python 2.7 as seen in https://github.com/conda/conda-pack/blob/7323db1bcc8016a3f7aea54c0d44c860de7387b3/.github/workflows/main.yml#L94 `conda` [dropped support for it with 4.10](https://github.com/conda/conda/releases/tag/4.10.0), thus I would also happily follow with that here.

@mcg1969 Would it you be OK with that?

**Comment by mcg1969** [comment]
Yes, I'm open to this. Are you seeing breakage _now_, or do you just anticipate it coming soon?

**Comment by xhochy** [comment]
This is in the context of https://github.com/conda/conda-pack/pull/172, I'm seeing there some (minor?) issues with Python 2 compatibility but I'm not really seeing any benefit of doing the extra work anymore. Thus I would rather spend the time and invest into the right `>=3` switches instead of keep doing these backports.
