### ISSUE TITLE
Update Instructions for Windows

### ISSUE THREAD

**Issue by Adam-D-Lewis** [conda/conda-pack#178]
Adding `activate` instructions (after untarring) for windows would be useful

From https://gist.github.com/pmbaumgartner/2626ce24adb7f4030c0075d2b35dda32
>7. (Target) Unpack the environment and activate it
Note: Be sure you're using standard Command Prompt (cmd.exe) on Windows, not Anaconda Prompt or PowerShell; those shells don't correctly add the right files to PATH.

>cd unpacked-environment
.\Scripts\activate.bat
.\Scripts\conda-unpack.exe

>8. (Target) Run Python in your unpacked-environment
The prompt should tell you that you're in the right environment after the last step, so you should see something like the following, which will allow you to then run python within this environment

>(unpacked-env-name) C:\Some\Path\Where\Your\Environment\Is> python

**Comment by liutiming** [comment]
Thanks @Adam-D-Lewis !
