### ISSUE TITLE
The determination of the full path of the activate script can lead to a wrong path

### ISSUE THREAD

**Issue by ehmoussi** [conda/conda-pack#180]
The `activate` script for linux can lead to a wrong full path for the script:
```full_path_script_dir="$(cd "${script_dir}" && pwd)"```

I used it in a machine where the command ```cd "${script_dir}"``` returns a value so I ended with `my/full/path my/full/path:/usr/local/bin:...` in my `PATH`

My workaround, if it can help, was to replace by:
```full_path_script_dir="$(cd "${script_dir}" > /dev/null && pwd)"```

**Comment by xhochy** [comment]
@ehmoussi Can you make a pull request with this please?
