### ISSUE TITLE
Conda-pack spyder issue

### ISSUE THREAD

**Issue by mnoel3** [conda/conda-pack#181]
I used conda pack to create a copy of my environnement on an offline machine. But spyder doesn't work in the new environnement, the following message appears when I tried to launch spyder in anaconda prompt : 

```
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect.
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
```

How can I fix this bug ? 
Thanks

**Comment by CA4GitHub** [comment]
In the env folder (e.g. `...\Anaconda3\envs\your_env_name\`) there should be a qt.conf file.  Edit the file to point to the appropriate directories.  I think you will probably need to do something like this... old qt.conf `Binaries=..\old_path\Library\bin`  Now change it so `Binaries= ...\Anaconda3\envs\your_env_name\Library\bin`

Alternatively, after unpacking the envrionment `conda create --clone your_env_name_clone  --name your_env_name` fixes the issue!  It appears that conda-pack doesn't handle config files pointing to dirs to well, but `conda create --clone` does.
