### ISSUE TITLE
The tool installed in Envs throw ModuleNotFoundError: on the target machine while the same tool on the source machine Envs running

### ISSUE THREAD

**Issue by chandanbfx** [conda/conda-pack#183]
Hi,

 I am trying to pack my environment with virsorter tool and unpack it on the target machine. On the source machine, it's running but after conda pack and unpack it throw ModuleNotFoundError on the target machine.

ubuntu : 16.04
pyyhon : 3.8
conda : 4.10.1 
conda-pack: 0.6.0

followed this link: https://conda.github.io/conda-pack/ to pack and unpack.

I am new to conda-pack, so please let me know if more details/information require.

thanks
chandan

**Comment by aurany** [comment]
Same issue here on Centos / ppc64le. Trying to pack dbt, airflow, prefect and some more packages. Running "python -c 'import dbt, prefect'" works fine but "python -c 'import airflow'" throws ModuleNotFoundError.

**Comment by aurany** [comment]
> Same issue here on Centos / ppc64le. Trying to pack dbt, airflow, prefect and some more packages. Running "python -c 'import dbt, prefect'" works fine but "python -c 'import airflow'" throws ModuleNotFoundError.

After a ”conda clean —all” and a reinstallation of the environment everything is working fine on the target machine.

**Comment by xhochy** [comment]
Can you post please post the output of `conda list` & `pip list` and the full traceback of the `ModuleNotFoundError` you are getting?

**Comment by chandanbfx** [comment]
Hi, 

It is fixed now sorry didn't update here.

1. The error was due to two different tools (virsorter and vcontact2 ) using two different Prerequisites.  
2. The error was due to a lack of compatibility between pandas(0.25.3) and NumPy(>=1.0.3) version 

thanks
chandan
