### ISSUE TITLE
Using conda pack in a github actions

### ISSUE THREAD

**Issue by hadim** [conda/conda-pack#184]
Does anyone have experience using conda pack within GitHub actions? I am trying to make some of our CIs faster. Currently using `conda-incubator/setup-miniconda@v2`, 90% of the time is taken by installing deps either from scratch or from the cache (using a cache sometimes takes longer than downloading from scratch).

There is a ticket opened in the `setup-miniconda` repo that I tried to use as a starting point to build a GA workflow but couldn't make it work: https://github.com/conda-incubator/setup-miniconda/issues/155#issuecomment-805226712

**Comment by hadim** [comment]
I guess the best would be for `conda-incubator/setup-miniconda@v2` to support `conda-pack` xD

**Comment by xhochy** [comment]
You probably don't need `conda-pack` for this but you could `tar` the environment, cache it and unpack it again in the action. In the action, you have the benefit that the environment is always at the same location. Thus you don't need the relocation magic of `conda-pack` at all.

**Comment by hadim** [comment]
I actually didn't realize that. That's a good point. Thank you @xhochy !

**Comment by bkreider** [comment]
Conda-pack acts just like a tar as mentioned above.  So you can use conda-pack to create the tar and then if you ever need to relocate or if new features are added to conda-pack, it will be easy to incorporate.
