### ISSUE TITLE
what may happend if original machine's environment differ from target machine?

### ISSUE THREAD

**Issue by ShadowTeamCN** [conda/conda-pack#185]
Example:
original: Ubuntu
target   : Centos / Windows

**Comment by xhochy** [comment]
Conda has very few outside dependencies. Main things that you need to be aware of:

- The target system might have an older glibc (only relevant for Linux), some packages might not work anymore. But most packages work on any Linux that is at least as new as CentOS 6, all of them work on CentOS 7
- You can only transfer environments on the same platform (platforms as in win-64/linux-64/linux-aarch64/osx-64/…).
- There are another small set of external things that could come in that you may also need to install on the target system if you are using them on the source. This is mostly CUDA or an X server. If you don't use them, you don't need them though.

**Comment by ShadowTeamCN** [comment]
> Conda environments have very few outside dependencies. Main things that you need to be aware of:
> 
> * The target system might have an older glibc (only relevant for Linux), some packages might not work anymore. But most packages work on any Linux that is at least as new as CentOS 6, all of them work on CentOS 7
> * You can only transfer environments on the same platform (platforms as in win-64/linux-64/linux-aarch64/osx-64/…).
> * There are another small set of external things that could come in that you may also need to install on the target system if you are using them on the source. This is mostly CUDA or an X server. If you don't use them, you don't need them though.

I got it , thanks a lot,
I migrant my deep learning environment from ubuntu to centos , consists of torch-gpu package. Since both orignal and target machine use the same CUDA and cuDNN, all things seems works fine
