### ISSUE TITLE
/tmp is too small

### ISSUE THREAD

**Issue by jyanga** [conda/conda-pack#191]
Is there a way to specify the location of the working area since my `/tmp` is too small?  I keep getting `OSError: [Errno 28] No space left on device` because my `/tmp` is too small for the package that I am creating.

**Comment by jcrist** [comment]
You should be able to select a different temp directory by setting the `TMPDIR` environment variable (see https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir).

```
$ TMPDIR="/path/to/your/tmpdir"  conda-pack ...
```

**Comment by jyanga** [comment]
@jcrist Thank you.  This worked.  :)
