### ISSUE TITLE
Release conda-pack v0.7.0 version on PyPI

### ISSUE THREAD

**Issue by salil-at** [conda/conda-pack#219]
Hello! 

It would be great if the new release (0.7.0) is also available through [PyPI](https://pypi.org/project/conda-pack/)

Thanks!

**Comment by djhoese** [comment]
Just curious and in the effort of keeping this issue not stale, what are the use cases where you install conda-pack from PyPI (`pip`) instead of `conda`/`anaconda`/`conda-forge`?

**Comment by adriangonz** [comment]
Hey @djhoese ,

In our case, we let people use conda-pack tarballs to provide their own custom environments. To test this out, within the project itself we install `conda-pack` from PyPI as a test dependency. 

https://github.com/SeldonIO/MLServer/blob/2c0ad7e127ed98913ac4743febd7d8373e0f073a/requirements/dev.txt#L22-L24

In the future, we may also add `conda-pack` as a core dependency to provide the packing functionality within our own CLI as well.

Thanks for that context @jcrist .

**Comment by jcrist** [comment]
>  If someone active on the conda project would like pypi permissions, I'd be happy to add them.

cc-ing @jezdez - is there someone (or someones) on the conda team that I should add here?

**Comment by xhochy** [comment]
I have manually uploaded all releases to PyPI and opened a PR to add the future releases on tag via trusted publishing: https://github.com/conda/conda-pack/pull/279
