### ISSUE TITLE
conda pack works, but unpack fails.

### ISSUE THREAD

**Issue by wcneill** [conda/conda-pack#220]
I just moved to a shared remote environment. One of my coworkers sent me a packed environment for our project and I copied it over to my personal user folder.

extracting and activating the environment went fine. However, unpacking failed. 

![image](https://user-images.githubusercontent.com/54779308/166815523-9780000f-7217-40e9-981f-099ba743bf09.png)

Another thing I noticed is that there is no `scripts` folder, which I was kinda expecting... everything appears to be in /bin/ instead.

**Comment by beeankha** [comment]
Hi @wcneill , thanks for filing this issue. We need some more information to pinpoint what exactly might be causing this problem. 

First off, please post the output that you get when you run:
```
$ tar tvf [conda pack tar.gz file]
```

Secondly, what happens if you `chmod u+x` that conda pack `tar.gz` file and try again?

**Comment by whimian** [comment]
> I just moved to a shared remote environment. One of my coworkers sent me a packed environment for our project and I copied it over to my personal user folder.
> 
> extracting and activating the environment went fine. However, unpacking failed.
> 
> ![image](https://user-images.githubusercontent.com/54779308/166815523-9780000f-7217-40e9-981f-099ba743bf09.png)
> 
> Another thing I noticed is that there is no `scripts` folder, which I was kinda expecting... everything appears to be in /bin/ instead.

Environments created under Linux have 'bin' directory, while those created under Windows have 'Scripts' directory.

**Comment by whimian** [comment]
```bash
(win) M:\HUB\Python\Downhole_Seismic_Test\envs\win>.\Scripts\conda-unpack.exe
Traceback (most recent call last):
  File "M:\HUB\Python\Downhole_Seismic_Test\envs\win\Scripts\conda-unpack-script.py", line 24613, in <module>
    placeholder, mode=mode)
  File "M:\HUB\Python\Downhole_Seismic_Test\envs\win\Scripts\conda-unpack-script.py", line 66, in update_prefix
    with open(path, 'rb+') as fh:
PermissionError: [Errno 13] Permission denied: 'M:\\HUB\\Python\\Downhole_Seismic_Test\\envs\\win\\python.exe'
```

When running conda-unpack.exe, a PermissionError is thrown.
