### ISSUE TITLE
Is it needed to run `conda-unpack` with squashfs ?

### ISSUE THREAD

**Issue by PhML** [conda/conda-pack#261]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I packed an environment into a squashfs archive and [mounted it into a singularity image](https://apptainer.org/docs/user/main/bind_paths_and_mounts.html#squashfs-image-files).

Do I need to run `conda-unpack` inside the container ?

This what I get when I try to launch it: 

```python
Traceback (most recent call last):
  File "/my-envs/bin/conda-unpack", line 391, in <module>
    update_prefix(os.path.join(new_prefix, path), new_prefix,
  File "/my-envs/bin/conda-unpack", line 66, in update_prefix
    with open(path, 'rb+') as fh:
         ^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/my-envs/lib/pkgconfig/sqlite3.pc'
```

The archive was created with `conda pack -n test_pack --format squashfs --n-threads 4 --compress-level 9`

**Comment by xhochy** [comment]
You need to mount a writable layer on top of the `squashfs` mount as described in https://conda.github.io/conda-pack/squashfs.html#making-the-unpacked-environment-writeable.

**Comment by PhML** [comment]
@xhochy
You are telling me that `conda-unpack` is necessary, right?

If possible, I would like to avoid the use of writable layer.

I understand that another option is to use the `--dest-prefix` flag. But if I use this flag, first, it doesn’t seems to compress the archive (see below), second Singularity tells me that image format [is] not recognized.

```
(myenv) visu06:~$ conda pack -n test_pack --format squashfs --n-threads 4 --compress-level 9 --output /scratch/packed_env.squashfs --dest-prefix /my-envs
Collecting packages...
Packing environment at '/scratch/conda/envs/test_pack' to '/scratch/packed_env.squashfs'
[########################################] | 100% Completed |  3.8s
(myenv) visu06:~$ rm /scratch/packed_env.squashfs
(myenv) visu06:~$ conda pack -n test_pack --format squashfs --n-threads 4 --compress-level 9 --output /scratch/packed_env.squashfs
Collecting packages...
Packing environment at '/scratch/conda/envs/test_pack' to '/scratch/packed_env.squashfs'
[########################################] | 100% Completed |  4.0s
Running mksquashfs with xz compression (processors: 4).
[==============================================================================================================================================|] 13445/13445 100%
```
