### ISSUE TITLE
Question about how conda pack works, why the pack step is necessary

### ISSUE THREAD

**Issue by jgarvin** [conda/conda-pack#336]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I would like to better understand what `conda-pack` does. My understanding is that `conda build` [already makes binaries relocatable by patching RPATH and other measures](https://docs.conda.io/projects/conda-build/en/stable/resources/make-relocatable.html). If this is the case, what extra work is pack/unpack doing? Why can't `conda build` do it?

**Comment by ncoghlan** [comment]
`conda-pack` and `conda build` work at different levels.

`conda-pack` packs an entire conda environment into a relocatable archive, not just a single conda package.

**Comment by jgarvin** [comment]
@ncoghlan thanks for the clarification, but that still leaves me wondering why `conda-pack` has anything to do, if all the packages inside the environment are all already individually relocatable? It sounds like you're implying I should be able to move `conda build` artifacts around without them breaking due to path assumptions, and a conda environment is a bunch of `conda build` artifacts, so I'm curious where the pathing assumptions get baked in?

**Comment by ncoghlan** [comment]
Most of what conda-pack does is simply making the archive itself. The work that `conda-unpack` does is mainly fixing shebang lines.

There is also some special case handling for various conda metadata files.

It's certainly possible to write your own code to do the same things that conda-pack does, and most things will still work correctly if you simply tar or zip the entire directory with no customisation of the input. conda-pack just tidies up the rough edges that arise when using a more simplistic approach.

The clearest documentation of exactly what those rough edges *are* is the conda-pack source code itself.

**Comment by jgarvin** [comment]
Thanks, I think that's enough for me to go on 👍
