### ISSUE TITLE
Would a refactor of conda-pack be welcome? 

### ISSUE THREAD

**Issue by kelvinou01** [conda/conda-pack#344]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Conda-pack is a really useful tool that solves a shortcoming of the conda ecosystem. However, as features and bugfixes are tacked onto the codebase throughout the years, it's grown quite a bit in complexity. 

I'm thinking about tidying up the conda-pack code. This means making the code easier to read, breaking big chunks of code into smaller pieces, and making sure everything is named clearly. I'd also like to add more comments to explain what different parts of the code do, and make sure we have tests to check everything is working right.

### Why is this needed?

This would mainly help people who want to add new things to conda-pack or fix problems. If the code is easier to read and understand, it's easier for people to start helping out. It could also mean we find and fix problems faster, and it's less likely that new changes will cause problems.

### What should happen?

For people using conda-pack, nothing should change. All the things they do with conda-pack now should still work the same way.

But for people working on conda-pack, they should find the code easier to understand and work with. It should be easier to find where to make changes, and there should be less chance of making mistakes.

I'm really keen to help out with this, but I wanted to check with you first. Would you be interested in me doing this work? And if so, is there anything specific you'd like me to do or not do?

Thanks for taking the time to think about this. I'm looking forward to hearing what you think.

**Comment by xhochy** [comment]
If you see things that could be improved, PRs are always welcome, and we can also give you feedback on small approaches. I can't give you any feedback on a general refactor, unfortunately. If things clearly improve, we can merge PRs, but be aware that just moving code around without any benefit in maintainability or functionality is not going to be merged or reviewed.
