### ISSUE TITLE
conda-pack documentation is outdated

### ISSUE THREAD

**Issue by saraedum** [conda/conda-pack#369]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The documentation https://conda.github.io/conda-pack/ seems to be outdated. It says that it's from 2017 at the bottom and it is missing some sections that have been added to the meantime.

---

This is a duplicate of #286 which was closed prematurely.

**Comment by jezdez** [comment]
Fixed via #377
