### ISSUE TITLE
Running '<env_path>/bin/python <envpath>/bin/conda-unpack' fails

### ISSUE THREAD

**Issue by bharathguvvala** [conda/conda-pack#40]
As suggested on the conda-pack documentation , running _conda-unpack_ without activating the environment (/tmp/XXXXXXX/bin/python /tmp/XXXXXXX/bin/conda-unpack) fails with the following error:

Traceback (most recent call last):
  File "/tmp/XXXXXXX/bin/conda-unpack", line 409, in <module>
    placeholder, mode=mode)
  File "/tmp/XXXXXXX/bin/conda-unpack", line 66, in update_prefix
    with open(path, 'rb+') as fh:
OSError: [Errno 26] Text file busy: '/tmp/XXXXXXX/bin/python3.6'

<img width="724" alt="image" src="https://user-images.githubusercontent.com/1975856/44533817-f74c7380-a713-11e8-8a27-09f0113f7d38.png">

PS: /tmp/XXXXXXX/bin/python is soft linked to /tmp/XXXXXXX/bin/python3.6

**Comment by jcrist** [comment]
Ah, good catch. This won't work, as the python in the environment is the entry point, and may be edited. Since the script uses `#!/usr/bin/env python`, it can be run without activating as long as another version of python is available. Fixed by #41.

**Comment by bharathguvvala** [comment]
FYI. This is only happening on linux and that too with python 3.6+ (definitely not 2.7).
