### ISSUE TITLE
conda-unpack failed

### ISSUE THREAD

**Issue by certik** [conda/conda-pack#47]
Steps to reproduce on the new machine:
```
$ mkdir antlr37
$ tar xzf antlr37.tar.gz -C antlr37
$ source antlr37/bin/activate
(antlr37) $ conda-unpack
Traceback (most recent call last):
  File "/users/certik/scratch1/pack/antlr37/bin/conda-unpack", line 408, in <module>
    placeholder, mode=mode)
  File "/users/certik/scratch1/pack/antlr37/bin/conda-unpack", line 66, in update_prefix
    with open(path, 'rb+') as fh:
OSError: [Errno 26] Text file busy: '/users/certik/scratch1/pack/antlr37/bin/python3.7'
```
I used the latest `conda-pack` available on conda forge. 

I didn't install Python nor conda on the target machine.

**Comment by certik** [comment]
According to [this](https://stackoverflow.com/questions/16764946/what-generates-the-text-file-busy-message-in-unix#16764967), this is because the Python file is used to execute `conda-unpack`, so it can't be modified...

**Comment by certik** [comment]
Indeed, that was it. The fix is to use a different Python to run it:
```
(antlr37) $ /usr/bin/python3.4 antlr37/bin/conda-unpack 
(antlr37) $
```

How should this be fixed?

**Comment by jcrist** [comment]
After talking to our build team and investigating the prefix in the binary, I've determined that the absolute path in the python executable is fine to ignore, and skipping it in `conda-unpack` is a valid solution.

**Comment by jcrist** [comment]
Fixed by #50. If you try installing from master things should work fine now. I hope to push a release in the next few days so you could also wait until the release.

**Comment by certik** [comment]
@jcrist would you mind pushing a release to conda-forge please? I just got burned by this bug again.

**Comment by jcrist** [comment]
Apologies, I thought I'd already released those fixes. Up on pypi, will be on conda-forge once the build finishes. Thanks for the reminder!

**Comment by certik** [comment]
Thanks!

**Comment by certik** [comment]
For reference, it's this PR to get it to conda-forge: https://github.com/conda-forge/conda-pack-feedstock/pull/6
