### ISSUE TITLE
Ensure roundtrip test would have caught unwritable binaries error in #47

### ISSUE THREAD

**Issue by certik** [conda/conda-pack#51]
The testing infrastructure failed to catch the bug reported in #47.

When looking at the tests, it seems they do not actually test relocating the environment, they only test individual parts of the package as specified in the tests here: https://github.com/conda/conda-pack/tree/60a814326c1200998362e856040d1a9d6b98d7dc/conda_pack/tests

As such, I think the tests should be updated to test that actually relocating the environment works, on Linux, Mac and Windows.

**Comment by jcrist** [comment]
There are several tests that test relocating an environment. For example: https://github.com/conda/conda-pack/blob/60a814326c1200998362e856040d1a9d6b98d7dc/conda_pack/tests/test_core.py#L213-L258. This tests packaging an environment, unarchiving it, and calling activate, conda-unpack, and deactivate.

The reason it failed to error is that the issue you're running into doesn't exist prior to 3.7. We currently only test with python 3.6 and python 2.7 environments, which work fine on all currently supported platforms. We should also test with a 3.7 environment, which would have caught that error.

**Comment by certik** [comment]
Ah ok. Thanks for the clarification.

**Comment by jcrist** [comment]
Hmmm, my investigation was incorrect (checked with the fix on master, not a previous commit). 

The test mentioned above should fail on 3.6 on linux as well but doesn't. I suspect the subprocess command in that test may not be selecting the proper `/usr/bin/env python` version, leading to it passing accidentally. I don't personally have time to investigate this, and don't suspect a bug in our application code, but there is a bug in the test code, leading to the test passing when it shouldn't be.
