### ISSUE TITLE
What is the motivation behind the tarball structure

### ISSUE THREAD

**Issue by certik** [conda/conda-pack#57]
Currently you have to unpack the tarball using:
```
$ mkdir -p my_env
$ tar -xzf my_env.tar.gz -C my_env
```
while the more common structure is to pack things into a subdirectory, as:
```
$ tar -xzf my_env.tar.gz
$ cd my_env
```
What are the motivation for the current format?

For my use case, when I want to distribute the tarball to users, the second option is better. I can of course repack it, but it would be better if conda-pack itself did it. Perhaps there can be an option how the tarball should be structured?

**Comment by jcrist** [comment]
The motivation is that this was originally written for deploying conda environments on hadoop clusters, and the cluster manager automatically unpacks tar balls into directories like:

```
mkdir -p dirname
tar -xzf dirname.tar.gz -C dirname
```

To change the structure of the tarball, use the [`arcroot`](https://conda.github.io/conda-pack/cli.html#cmdoption-conda-pack-arcroot) parameter or flag:

```
conda-pack --arcroot dirname -o dirname.tar.gz
```

**Comment by jcrist** [comment]
@certik, does the current solution work for you?

**Comment by certik** [comment]
I am testing it now.

**Comment by certik** [comment]
Ok, the `--arcroot dirname` works for me. Thanks!
