### ISSUE TITLE
Qt setup not restored correctly

### ISSUE THREAD

**Issue by durden** [conda/conda-pack#67]
I've been using `conda-pack` on Windows 10 with great results. Such a useful tool!  I did run into an issue when trying to unpack and use Spyder from a previous environment.  The qt.conf file had the old paths in it even after I ran `conda-unpack` on the new machine.  I kept getting errors trying to launch Spyder until I set `QT_PLUGIN_PATH` to the new location of the environment.

For example, the *host* machine's environment was packed up from `C:\Users\durden\AppData\Local\Continuum\miniconda2\envs\myenv`.  Then, I unpacked everything on a new machine and was testing the install in a different path (because I don't want the path hard-coded to my username).  So, I had to do the following to get Spyder working after unpacking:

`set QT_PLUGIN_PATH = C:\Python\myenv\Library\plugins`

Should conda-pack do this automatically when calling `unpack`?  Not sure where the responsibility for this should be, but thought I'd open it up for discussion so others can see what the temporary fix is.

**Comment by jcrist** [comment]
Apologies for the delayed response here. A few thoughts/questions:

- Is `QT_PLUGIN_PATH` set in the originating environment once activated? On my system I don't see it, but this may be version/package specific.
- We support activate hooks (same as conda), so certain scripts can be run during activation/deactivation to set/remove environment variables. I don't see any in the conda recipes for `pyqt`/`qt`/`qtpy`/`spyder` though. If these are present and not running, then this is a bug in conda-pack
- If the environment variable is normally unset, this means the plugin path must be hardcoded somewhere in the package. We should be doing prefix replacement to correct for this, but we may have a bug.

What would be most helpful would be a set of commands to reproduce this issue.

**Comment by Ossit** [comment]
I ran into the same issue with pyside2. 

This fails when moved to a second Windows 10 machine
`
conda create --name qt_test python=3.8

conda activate qt_test

conda install -c conda-forge pyside2
conda pack -n qt_test
`

This, on the other hand, works:
conda create --name qt_test python=3.8
conda activate qt_test
pip install pyside2
conda pack -n qt_test

**Comment by mcg1969** [comment]
I suspect this is partially duplicated by #141 and #154.
