### ISSUE TITLE
fail to pack env in Mac caused by paython.app and anaconda-anvigator

### ISSUE THREAD

**Issue by blesssecret** [conda/conda-pack#68]
when I run command: conda pack -n ml_env -o out_ml_env.tar.gz
I got the following error message:
CondaPackError: 
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- python.app=u'2'
- anaconda-navigator=u'1.9.7'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).

Python.app are depend on many package, cannot delete it from conda.

**Comment by jcrist** [comment]
Apologies for the delayed response. Can you provide the commands to reproduce the environment that failed here? Something like:

```
$ conda create -n myenv ... # command to create the environment
$ conda pack -n myenv       # packaging command, and error that shows the issue
```

**Comment by cjh1** [comment]
I am running into the same issue. Here is a simple way to reproduce the issue:

```
conda create -n pack-test
conda install -n pack-test --channel conda-forge python.app
conda pack -n pack-test
```

**Comment by cjh1** [comment]
@jcrist I did a little digging and it looks like all the file in `python.app` are being reported a missing [here](https://github.com/conda/conda-pack/blob/master/conda_pack/core.py#L748). I don't know enough about conda packaging to know why. Let me know if there is more information I can help with to get this resolved.

**Comment by cjh1** [comment]
@blesssecret Did you ever find a fix for this issue?

**Comment by cjh1** [comment]
Ok, so I have looked into this some more and it looks like `python.app` is being explicitly excluded from the list of files return by [load_files](https://github.com/conda/conda-pack/blob/master/conda_pack/core.py#L579). Removing it from the list allow `conda pack` to successfully package the environment. @jcrist What is the reason for `python.app` being in this list?

**Comment by mcg1969** [comment]
Folks, here's the reason why this isn't working.

Install the `python.app` package and take a look at its unpacked version inside the package cache; e.g.,
```
cd miniconda3/pkgs/python.app-1.3-py38h64e0658_1 
```
Of course, your exact path and filename may vary. Here's what you see at the top level if you `ls` that directory:
```
bin    info    pythonapp
```
But in fact, when you look at this _installed into the environment_, it's "Python.app", not "pythonapp". Why is this? Well, the package's post-link script has the answer:
```
#!/bin/bash

cp -r "$PREFIX/pythonapp" "$PREFIX/python.app"
rm -rf "$PREFIX/pythonapp"

cd "$PREFIX/python.app/Contents"
ln -s ../../lib .
```
For whatever reason, the package can't include the actual directory tree for Python.app, it has to create it dynamically for some reason. I don't understand why this is, but this is what confuses conda-pack. In short, conda-pack cannot handle packages that do this kind of magical renaming at the post-link level.

**Comment by mcg1969** [comment]
I'm open to suggestions about how this can be fixed but frankly I think that conda-pack is the wrong tool for this job. This seems like something that constructor should be used for instead, because it actually uses conda to perform the installation, enabling it to execute post-link scripts.
