### ISSUE TITLE
Incompatible/buggy tar file created under windows when hardlinks encountered

### ISSUE THREAD

**Issue by rahrah** [conda/conda-pack#70]
Hi,

It seems there's a bug in conda-pack tarfile when creating
archives under windows containing hardlinked files.

Bug creates errors and exit code 2 when unpacking using gnu tar
and failure to untar the whole archive when unpacking using 7zip.

The final gnu tar error is:

tar: Exiting with failure status due to previous errors

The intermediate gnu tar errors are of the form:

tar: Skipping to next header

OS: Windows 10 as archiver

Versions:

```
Conda: 4.6.14
Python: Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
conda-pack 0.3.1
```
Steps to reproduce:

```
Install miniconda under windows

conda create --name testenv
conda install -c conda-forge conda-pack
conda update --all
conda activate testenv
conda install sphinx
conda deactivate
conda pack -n testenv -o testenv.tgz
```
Then unpack `testenv.tgz` with gnu tar under Linux.

The files that cause the error are hardlinked.
For example these files in envs/testenv/Scripts:

```
74,752 sphinx-apidoc.exe
74,752 sphinx-autogen.exe
74,752 sphinx-build.exe
74,752 sphinx-quickstart.exe
```

There are a number of reports of similar errors in python tarfile, it
seems.  It might be good to warn of probs with hardlinked files using
tar formats under Windows.

Thanks for coda-pack!

===Rich

Updated 12may19

**Comment by jcrist** [comment]
Hmmm, good to know. I have seen this, but not all the time, and not necessarily using hard links. Thanks for the heads up. In the future we may switch to using `libarchive` to manage all archives, which might alleviate the problem.

**Comment by nugend** [comment]
Hi, seeing this on Linux as well.

**Comment by mcg1969** [comment]
I'm fixing the Windows issue for now by setting `dereference=True` on Windows. Will revisit this with libarchive.
