### ISSUE TITLE
add the new unpack env to Conda env list

### ISSUE THREAD

**Issue by arita37** [conda/conda-pack#73]
When doing conda env list, we cannot see the new unpack environnement,
can you add a way to add it ?

**Comment by jcrist** [comment]
`conda-pack` is primarily designed for deploying production environments. It *can* be compatible with conda, but that's not its primary use case. Environments unpacked and used with an external conda installation may not work correctly (note that if the packaged environment has conda installed inside it, using that conda should work fine). Given this, I'd be against automatically adding an unpacked environment to the environment list for an external conda. Users can add it themselves if they want by adding the path to `~/.conda/environments.txt`.

**Comment by mcg1969** [comment]
I agree with @jcrist on this one—`conda-pack` environments are not full-fledged conda environments. They are intended to be standalone. That is not to say this cannot be changed, but I too would prefer that it not be the default behavior.

I'm going to close this issue for cleanliness but I would be happy to entertain a PR that, say, allows `conda_unpack` to accept a command-line option to add the environment to a local conda installation.

I would be concerned, however, that conda's activate/deactivate scripts might interfere with those found in the unpacked environment. That would need to be properly addressed by any PR.
