### ISSUE TITLE
Apply techniques for making smaller conda environments

### ISSUE THREAD

**Issue by djhoese** [conda/conda-pack#74]
How possible would it be to migrate some of the techniques described in https://jcrist.github.io/conda-docker-tips.html to reduce the size of the tarball. I suppose it would be best to make a command line option for this if it doesn't already exist.

1. `conda clean -afy
2. Remove select file types: `.js.map`, `.pyc`, `.a`, and bokeh's unminified .js files.

**Comment by jcrist** [comment]
- Conda clean is unnecessary, as the package cache/metadata should never be part of the tarball
- Removing certain file types is already possible with the `--exclude`/`--include` flags (https://conda.github.io/conda-pack/cli.html#cmdoption-conda-pack-exclude).

```
conda pack \
  --exclude *.js.map \
  --exclude *.pyc \
  --exclude *.a
```

**Comment by djhoese** [comment]
Right, I guess I was hoping for an all-in-one "conda-pack knows best" option. Feel free to close.

**Comment by jcrist** [comment]
I don't think we can provide that, as any one of those file extensions may actually be important. There is also an added maintenance cost to adding additional flags.
