### ISSUE TITLE
Packing an environment including `conda` results in duplicate files in the archive

### ISSUE THREAD

**Issue by angelo-peronio** [conda/conda-pack#88]
If an environment containing `conda` is packaged, the resulting archive contains two different `activate.bat`, I suppose one from `conda`, the other from `conda-pack`.

 * Is this unavoidable?
 * I noticed this behaviour only when decompressing the archive. It would be great to be warned during the packaging process.

### What I am trying to achieve
I need to deploy a Python environment to a production machine with no Internet connection. Having `conda` in the environment would allow me to quickly update a package using a custom offline channel, e.g. on an USB stick.

### Steps to reproduce
```
conda create --name test-env conda

conda pack --name test-env

tar -tzf test-env.tar.gz | sort | uniq --count --repeated
    2 Scripts/activate.bat
```

### Output of `conda info`
```
     active environment : packaging
    active env location : C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3\envs\packaging
            shell level : 1
       user config file : C:\Users\angelo.peronio\.condarc
 populated config files : C:\Users\angelo.peronio\.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\angelo.peronio\.conda\pkgs
                          C:\Users\angelo.peronio\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\angelo.peronio\.conda\envs
                          C:\Users\angelo.peronio\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by jcrist** [comment]
Tar files allow layering - files added layer overwrite files added earlier. Conda-pack adds its files at the end without filtering the filenames earlier to make our code simpler. This shouldn't affect use, the later filename will be the correct one. Are you running into issues because of this?

**Comment by angelo-peronio** [comment]
Jim, thank you!

No issues, indeed. The following warnings made me believe that something was not right:

* While packing
    ```
    conda pack --name test-env --output test-env.zip
    Collecting packages...
    Packing environment at 'C:\\Users\\angelo.peronio\\AppData\\Local\\Continuum\\miniconda3\\envs\\test-env' to 'test-env.zip'
    [####################################### ] | 99% Completed | 26.0sC:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3\envs\packaging\lib\zipfile.py:1473: UserWarning: Duplicate name: 'Scripts/activate.bat'
      return self._open_to_write(zinfo, force_zip64=force_zip64)
    [########################################] | 100% Completed | 26.1s
    ```

* While unpacking with 7-Zip 19.00 on Windows:
![7zip-warning](https://user-images.githubusercontent.com/22264609/64242331-9f8b3f80-cf05-11e9-85d2-3822c540e251.png)

I understand now that this behaviour is expected. Maybe it is worth mentioning it in the documentation? Feel free to close the issue.

**Comment by mcg1969** [comment]
I'm going to leave the issue open since the behavior seen by 7-Zip is not desirable. I'd invite anyone to submit a PR to deduplicate files before packing.

**Comment by screig** [comment]
This causes me a problem,

The file 'C:\Users\Sean\AppData\Local\Temp\conda_venv_38_x64__1.23.4\Lib\site-packages\pycparser\__pycache__\__init__.cpython-38.pyc' already exists.  

I would like to remove these files before I try and extract them.
