### ISSUE TITLE
conda create with python2.7 base still creates python3.6 environment by default

### ISSUE THREAD

**Issue by mattf-apache** [conda/conda-pack#90]
If one downloads Miniconda2-latest-MacOSX-x86_64.sh and runs it, you get as expected a python2.7 base environment.  Go ahead and activate it, then invoke `conda create` with a few packages, but without specifying a version of python.  It builds a python3.6 environment.

I could not find documentation one way or the other, but I did expect it to give me another python2.7 environment, especially since I had activated the base environment before invoking `conda create`.

**Comment by marcelotrevisani** [comment]
Basically ``conda`` will try to get the latest package of all of those which you are trying to install.
However, if you want a conda environment with a specific python you can do
```
conda create --name env-test python=2.7 pytest 
```

**Comment by marcelotrevisani** [comment]
Did I clarify your question? May I close this or do you want to discuss it a bit further?

**Comment by jcrist** [comment]
This has nothing to do with `conda-pack`, this has to do with usage of conda. If you want to create a python environment with a specific version of Python, you need to specify that manually as @marcelotrevisani said above. Closing.

**Comment by mattf-apache** [comment]
So be it.  This was to suggest that a more intuitive behavior was to give the same version as the base, by default. But it's also reasonable for `conda` to always use the latest, regardless of base.
