### ISSUE TITLE
windows PermissionError matplotlib pdf

### ISSUE THREAD

**Issue by hyamanieu** [conda/conda-pack#91]
I am trying to pack an environment contaning matplotlib. For some reason it throws a permission error pointing to a pdf although I have full read/write/exec access to the whole folder.

`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\hy.amanieu\\AppData\\Local\\Continuum\\anaconda3\\pkgs\\matplotlib-3.1.0-py37hc8f65d3_0\\Lib/site-packages/matplotlib/mpl-data/images/back.pdf'`

I could however pack the environment when going through python and import conda_pack.
OS is windows 10.

**Comment by xhochy** [comment]
This could be a typical file-opened-by-other-process issue, thus: does the problem persist after rebooting?

**Comment by mcg1969** [comment]
I created an environment with this exact package and was able to successfully pack it and unpack it with the current head of conda-pack. I also verified importing matplotlib, and opening the `back.pdf` file in an application. I'm going to close this but please feel free to re-open if we can gather more evidence there is still an issue.
