### ISSUE TITLE
Please add an option to not modify PS1

### ISSUE THREAD

**Issue by nugend** [conda/conda-pack#92]
Regular conda has this, it'd be very nice if the activate/deactivate scripts could either be modified on creation in the redistributable archive or otherwise respect an environment variable or something along those lines.

Thank you.

**Comment by jcrist** [comment]
Can you clarify what you're need is here? Do you want `conda-pack` activate scripts to not modify PS1, or do you want the PS1 formatted differently?

**Comment by nugend** [comment]
The former.

**Comment by jcrist** [comment]
Sure. I'd probably do this with an environment variable that the `activate` script looks for. PRs welcome.
