### ISSUE TITLE
conda-unpack.exe does not work for 32-bit windows

### ISSUE THREAD

**Issue by johanjeppsson** [conda/conda-pack#93]
When packing a 32-bit windows environment, I am unable to run conda-unpack.exe, which I assume is due to it being a 64-bit executable. The packed environment itself seems to work fine.

I had a look and came up with something like [this](https://github.com/johanjeppsson/conda-pack/commit/eb76175d48248a91ed20a9ff8a4d5b0ac0a4be72), but I am unsure if this is the way to go, and how to ensure that I don't break anything. Any suggestions?

**Comment by mcg1969** [comment]
@johanjeppsson I know this is super-stale but I'd welcome a PR on this and can test it.

**Comment by mcg1969** [comment]
oops, didn't mean to close!

**Comment by johanjeppsson** [comment]
Sorry, I forgot to link it, but I submitted a pull request for this that was merged [here](https://github.com/conda/conda-pack/pull/94)
