### ISSUE TITLE
How to replicate your R example using SparkR and not Sparkly R

### ISSUE THREAD

**Issue by lek18** [conda/conda-pack#97]
Hello,

I followed the steps outlined here : https://conda.github.io/conda-pack/spark.html for distributing a Conda r env in spark and it worked! I am attempting to replicate the same with SparkR but not being able to. 

I have completed the following:
conda create -p /home/ubuntu/r_env --copy -y -q r-essentials -c r
conda install conda-pack

conda activate example
conda pack -o environment.tar.gz -d ./environment

and I am unsure if the following spark session is correct:

library(SparkR)
sparkR.session(master = "yarn",sparkConfig = list(
                                                      spark.yarn.dist.archives="environment.tar.gz#environment",
                                                      spark.num.executors="3",
                                                      spark.executor.cores="3",
                                                      spark.executor.memory="6G",
                                                      spark.r.command = "./environment/bin/Rscript",
                                                      spark.yarn.appMasterEnv.R_HOME="./environment/lib/R",
                                                      spark.yarn.appMasterEnv.RHOME = "./environment",
                                                      spark.yarn.appMasterEnv.R_SHARE_DIR = "./environment/lib/R/share",
                                                      spark.yarn.appMasterEnv.R_INCLUDE_DIR = "./environment/lib/R/include",
                                                      spark.yarn.executorEnv.R_HOME="./environment/lib/R",
                                                      spark.yarn.executorEnv.RHOME = "./environment",
                                                      spark.yarn.executorEnv.R_SHARE_DIR = "./environment/lib/R/share",
                                                      spark.yarn.executorEnv.R_INCLUDE_DIR = "./environment/lib/R/include"
                                                      ))

**Comment by jcrist** [comment]
Glad the sparklyr example worked for you. I'm not familiar with `SparkR`, so I'm not sure why the above wouldn't work (sorry). Nothing explicitly looks wrong.

cc @ericdill - I think I remember you used conda-pack with spark and R at some point? Any knowledge of SparkR?

**Comment by lek18** [comment]
@jcrist Thanks for the quick reply! I was able to make it work. The trick was to include the tar ball in --archives and not in yarn.dist.archives

sparkR \
--master yarn \
--conf spark.r.command=./environment/bin/Rscript \
--conf spark.yarn.appMasterEnv.R_HOME=./environment/lib/R \
--conf spark.yarn.appMasterEnv.RHOME=./environment \
--conf spark.yarn.appMasterEnv.R_SHARE_DIR=./environment/lib/R/share \
--conf spark.yarn.appMasterEnv.R_INCLUDE_DIR=./environment/lib/R/include \
--conf spark.executorEnv.R_HOME=./environment/lib/R \
--conf spark.executorEnv.RHOME=./environment \
--conf spark.executorEnv.R_SHARE_DIR=./environment/lib/R/share \
--conf spark.executorEnv.R_INCLUDE_DIR=./environment/lib/R/include \
--deploy-mode client \
--num-executors 3 \
--executor-cores 3 \
--archives environment.tar.gz#environment
